// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdtBYQtv7o29Ey3sa7jOdx4eLrJqX3Pk8',
    appId: '1:828957679453:web:f7f2ea0adc41d61f6d12b4',
    messagingSenderId: '828957679453',
    projectId: 'connecting-gsitians',
    authDomain: 'connecting-gsitians.firebaseapp.com',
    storageBucket: 'connecting-gsitians.appspot.com',
    measurementId: 'G-Q3TBXE3V3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQ0nH_iwRU3gxrtmlqmZY8tAU0Avw6-Q',
    appId: '1:828957679453:android:df581ae4bc3753876d12b4',
    messagingSenderId: '828957679453',
    projectId: 'connecting-gsitians',
    storageBucket: 'connecting-gsitians.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_hnFIzOz1wrp-Wmpx_Xpvdr6_rozJaY',
    appId: '1:828957679453:ios:9244bc76dcd26d4b6d12b4',
    messagingSenderId: '828957679453',
    projectId: 'connecting-gsitians',
    storageBucket: 'connecting-gsitians.appspot.com',
    androidClientId: '828957679453-scmgpkn69fi5qmg6k5m53g4ls6p2in9k.apps.googleusercontent.com',
    iosClientId: '828957679453-ui81jsa36rnrqopimt44l7prr0dfgbkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_hnFIzOz1wrp-Wmpx_Xpvdr6_rozJaY',
    appId: '1:828957679453:ios:9244bc76dcd26d4b6d12b4',
    messagingSenderId: '828957679453',
    projectId: 'connecting-gsitians',
    storageBucket: 'connecting-gsitians.appspot.com',
    androidClientId: '828957679453-scmgpkn69fi5qmg6k5m53g4ls6p2in9k.apps.googleusercontent.com',
    iosClientId: '828957679453-ui81jsa36rnrqopimt44l7prr0dfgbkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
